In [78]:
import pandas as pd
import numpy as np
pd.__version__

'3.0.6'

In [79]:
df = pd.read_csv("../car_fuel_efficiency_2026.csv")

In [80]:
df.shape

(10000, 11)

In [81]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [82]:
df['fuel_type'].nunique()

3

In [83]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [84]:
df['fuel_efficiency_mpg'].groupby(df['origin']).max()

origin
Asia      41.2
Europe    39.4
USA       38.2
Name: fuel_efficiency_mpg, dtype: float64

In [85]:
df['horsepower'].median()

np.float64(254.0)

In [86]:
df['horsepower'].value_counts().sort_values(ascending=False)

horsepower
252.0    174
246.0    168
256.0    168
259.0    165
253.0    165
        ...
322.0      1
330.0      1
175.0      1
178.0      1
320.0      1
Name: count, Length: 153, dtype: int64

In [87]:
df['horsepower'] = df['horsepower'].fillna(252.0)

In [88]:
df['horsepower'].median()

np.float64(252.0)

In [89]:
X = df[df.origin == 'Asia'][['vehicle_weight', 'model_year']].head(7)
X

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [90]:
XTX = (X.T).dot(X)
XTX

                vehicle_weight  model_year
vehicle_weight       131950500    60750580
model_year            60750580    28041424

In [91]:
XTX_inv = np.linalg.inv(XTX)

In [92]:
y = [1100, 1300, 800, 900, 1000, 1100, 1200]
w = (XTX_inv.dot(X.T)).dot(y)

In [93]:
w.sum()

np.float64(0.36919696904925486)